controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
contact_submit:
    path: /contact/submit
    controller: App\Controller\ContactController::submit
    methods: [POST]